language: java

before_install: 
 - openssl aes-256-cbc -K $encrypted_432bca9ab536_key -iv $encrypted_432bca9ab536_iv -in jaime-aws.pem.enc -out jaime-aws.pem -d
 - chmod +x gradlew

script: 
 - ./gradlew build

after_success:
  - "scp -i ~/Documents/Bridgephase/GSA_BPA/jaime-aws.pem ./build/libs/javastarter.war ubuntu@ec2-54-164-139-179.compute-1.amazonaws.com:/home/ubuntu"
# - "curl -v -u $FTPUSER:$FTPPASSWORD ftp://waws-prod-blu-027.ftp.azurewebsites.windows.net/ -Q 'DELE site/wwwroot/webapps/javastarter.war'" 
# - "curl --ftp-create-dirs -T ./build/libs/javastarter.war -u $FTPUSER:$FTPPASSWORD ftp://waws-prod-blu-027.ftp.azurewebsites.windows.net/site/wwwroot/webapps/"