language: java

before_install: 
 - openssl aes-256-cbc -K $encrypted_432bca9ab536_key -iv $encrypted_432bca9ab536_iv -in jaime-aws.pem.enc -out jaime-aws.pem -d
 - chmod +x gradlew

script: 
 - ./gradlew build

deploy:
  provider: codedeploy
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_KEY
  bucket: "jgr-deployments"
  key: ./build/libs
  application: JavaStarter
  deployment_group: TestDeploys